### ISSUE TITLE
Automatic creation of PRs for updated / new branches?

### ISSUE THREAD

**Issue by ghost** [Mergifyio/mergify#35]
Would love to implement a really easy flow for a project:

1. Automatically create PR
2. Automatically merge it (no requriements have to be met)

**Comment by jd** [comment]
@MangoSmoothie101010 would this "auto merge any pull request" or only certain pull requests? How would you identify them?

**Comment by MangoSmoothie101010** [comment]
@jd The use-case I'm having are glitch.com exports. They are exported to the `glitch` branch and then I merge `glitch` into `master` to trigger heroku autodeployment.

I would like to create a pull request automatically for every new changes to `glitch` that are ahead of `master` and merge them. 

I'd identify the PRs to merge by looking at their `source` and `target` branch, which would need to match `glitch` and `master` in this case.

I could also change the branch heroku is watching to `glitch`, that'd be easier. But I actually like the separation.

**Comment by jd** [comment]
I'm not sure about the automatic PR creation, in the sense that it's not the core of what we're trying to do here.

However, automatically merging certain PR without review (once CI is passed if there's one) is also something that has been requested as part as #42, so that sounds like a good feature.
