### ISSUE TITLE
Mergify has created two PRs from the same branch on `backport` action

### ISSUE THREAD

**Issue by jakelishman** [Mergifyio/mergify#5066]
## Expected Behavior

On backport, a single branch should be created, and the Mergify bot should open a single PR from it to the target branch.

## Actual Behavior

I've just had an example where Mergify created a single branch, but then opened two separate PRs from it to the same target branch.  (I didn't even know that was possible on GitHub - it's possible it's a GH bug and not a mergify one.)

## Steps to Reproduce the Problem

I'm not sure - it's just happened once, with no changes to the Mergify configuration since the last successful action (a couple of hours prior to the "failure").

## Specifications

  - Pull Request URL: https://github.com/Qiskit/qiskit-terra/pull/9496 and https://github.com/Qiskit/qiskit-terra/pull/9497
  - Mergify Config URL: https://github.com/Qiskit/qiskit-terra/blob/06f5ac1e8d7cbf4dcd157c127911f83c1e43e6ae/.mergify.yml

**Comment by jd** [comment]
Hi @jakelishman 

Thanks for reporting the issue. We've looked into that.
It turns out Mergify did everything right, but the first backport PR request has timed out. Mergify considered this as "not working" and retried a few seconds later the same request, which created the "real" backport as far as Mergify is concerned.

![CleanShot 2023-02-01 at 12 50 02](https://user-images.githubusercontent.com/2644/216035153-4a9daa55-0ebe-4bde-b08d-efdd1748e2d6.png)

Let's hope the Internet does not break too often.
